//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface Books_Create_Request {
    title: string;
    author: string;
    isbn: string;
    publishedDate: string;
}

export interface Books_Create_Response {
    id: string;
    title: string;
}

export interface Books_GetAll_Response {
    books: BookDetails[];
}

export interface Books_GetById_Response {
    book: BookDetails;
}

export interface Books_Search_Response {
    books: BookDetails[];
}

export interface Books_UpdateById_Request_UpdatedDetails {
    title?: string | undefined;
    author?: string | undefined;
    isbn?: string | undefined;
    publishedDate: string;
}

export interface Borrow_BorrowBook_Request {
    reservationId: string;
}

export interface Borrow_BorrowBook_Response {
    borrowDetails: BorrowDetails;
}

export interface Borrow_GetAll_Response {
    books: BorrowDetails[];
}

export interface Borrow_GetByCustomerId_Response {
    reservations: BorrowDetails[];
}

export interface Customers_GetAll_Response {
    customers: CustomerDetails[];
}

export interface Reservations_GetAll_Response {
    books: ReservationDetails[];
}

export interface Reservations_GetById_Response {
    reservation: ReservationDetails;
}

export interface Reservations_GetReservationsByCustomerId_Response {
    reservations: ReservationDetails[];
}

export interface Reservations_MakeReservation_Request {
    customerId: string;
    bookId: string;
}

export interface Reservations_MakeReservation_Response {
    reservationDetails: ReservationDetails;
}

export interface BookDetails {
    id: string;
    title: string;
    author: string;
    isbn: string;
    status: string;
    publishedDate: string;
}

export interface BorrowDetails {
    borrowId: string;
    customerId: string;
    bookId: string;
    title: string;
    borrowDate: string;
    dueDate: string;
}

export interface CustomerDetails {
    id: string;
    email: string;
    firstName: string;
    lastName: string;
    primaryAddress?: AddressDetails | undefined;
    phoneNumber?: string | undefined;
    createdAt: string;
}

export interface AddressDetails {
    street: string;
    city: string;
    state: string;
    country: string;
    zipCode: string;
}

export interface ReservationDetails {
    reservationId: string;
    bookId: string;
    customerId: string;
    title: string;
    reservedDate: string;
    expiryDate: string;
}

export interface ProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;
}