//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface Books_Create_Request {
    title: string;
    author: string;
    isbn: string;
    publishedDate: string;
}

export interface Books_Create_Response {
    id: string;
    title: string;
}

export interface Books_GetAll_Response {
    books: BookDetails[];
}

export interface Books_GetById_Response {
    book: BookDetails;
}

export interface Books_Search_Response {
    books: BookDetails[];
}

export interface Books_UpdateById_Request_UpdatedDetails {
    title?: string | undefined;
    author?: string | undefined;
    isbn?: string | undefined;
    publishedDate: string;
}

export interface BookDetails {
    id: string;
    title: string;
    author: string;
    isbn: string;
    publishedDate: string;
}

export interface ProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;
}